logging.level.com.github.patbattb.tgbot.service=debug

spring.datasource.url=jdbc:postgresql://localhost:5432/patbat
spring.datasource.username=patbat
spring.datasource.password=patbat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


